apiVersion: v1
kind: Pod 
metadata:
  name: empty-dir-demo 
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-logs
      mountPath: var/logs/nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]
    volumeMounts:
    - name: nginx-logs
      mountPath: mnt/nginx/logs
      readOnly: true
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 500Mi