
#create PV is admin job
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #Retain means don't delete the data, Recycle means delete data and don't delete the disk, Delete means delete the disk
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0aab56e7ca6b52899
  
---
# create PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

# ---
# # create POD
# apiVersion: v1
# kind: Pod 
# metadata:
#   name: nginx
#   labels:
#     purpose: ebs-static
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:
#     - name: nginx-html
#       mountPath: usr/share/nginx/html
#   nodeSelector:
#     topology.kubernetes.io/zone: us-east-1b

#   volumes:
#   - name: nginx-html
#     persistentVolumeClaim: 
#       claimName: ebs-static
# ---
# # create service loadbalancer
# apiVersion: v1
# kind: Service
# metadata: 
#   name: nginx-ebs-static
# spec:
#   type: LoadBalancer
#   selector:
#     purpose: ebs-static
#   ports: 
#   - protocol: TCP
#     port: 80
#     targetPort: 80
#     nodePort: 30007
