apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop-sc
  resources:
    requests:
      storage: 4Gi

---
# create POD
apiVersion: v1
kind: Pod 
metadata:
  name: nginx
  labels:
    purpose: ebs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: user/share/nginx/html
  # nodeSelector:
  #   topology.kubernetes/io/zone: us-east-1b
  volumes:
  - name: nginx-html
    persistentVolumeClaim: 
      claimName: ebs-dynamic
---
# create service loadbalancer
apiVersion: v1
kind: Service
metadata: 
  name: nginx-ebs-dynamic
type: LoadBalancer
spec:
  selector:
    purpose: ebs-dynamic
  ports: 
  - protocal: TCP
    port: 80
    targetPort: 80
    nodeport: 30007
