apiVersion: v1
kind: Pod
metadata:
  name: mulit-container
  labels:
    purpose: mulit-container
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]
