apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
    project: roboshop
    environment: dev 
    version: v1
spec:
  containers:
  - name: frontend
    image: nginx