apiVersion: v1
kind: Pod
metadata: 
  name: resources-demo 
spec:
  containers: 
  - name: nginx
    image: nginx 
    resources:
      # Soft limit
      requests:
        memory: "68Mi"
        cpu: "100m"
      # Hard limit
      # you can give equal or greater than requests
      limits:
        memory: "100Mi"
        cpu: "120m"
