apiVersion: v1
kind: Pod 
metadata:
  name: service-demo
  # these labels are used to register this Pod with service
  labels:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx