apiVersion: v1
kind: Service
metadata: 
  name: service-np 
spec: 
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    environment: dev 
    purpose: node-port
  ports: 
  - port: 80 #serive port
    targetPort: 80 #container port
    # will allocate a port from a range (default: 30000-32767) 
    nodeport: 30007