apiVersion: v1
kind: Service
metadata: 
  name: nginx-lb
type: LoadBalancer
spec:
  selector:
    project: roboshop
    environment: dev
    component: frontend
    purpose: load-balancer
  ports: 
  - protocal: TCP
    port: 80
    targetPort: 80
    nodeport: 30007
